#!/bin/sh
#
# Configure USB gadget interfaces
#

SERIAL_NUMBER="1234567890"
MANUFACTURER="Raspberry Pi"
PRODUCT="Android Auto Wireless"

VENDOR_ID="0x22d9"
PRODUCT_ID="0x2764"

ACCESSORY_GADGET_NAME="accessory"
DEFAULT_GADGET_NAME="default"

RETVAL=0

start() {
	mountpoint -q /sys/kernel/config || mount -t configfs none /sys/kernel/config

	# Setup accessory config
	cd /sys/kernel/config/usb_gadget
	if [ ! -d "$ACCESSORY_GADGET_NAME" ]; then
		mkdir "$ACCESSORY_GADGET_NAME"
		cd "$ACCESSORY_GADGET_NAME"
		echo "0x18D1" > idVendor
		echo "0x2D00" > idProduct
		mkdir strings/0x409
		echo "$SERIAL_NUMBER" > strings/0x409/serialnumber
		echo "$MANUFACTURER" > strings/0x409/manufacturer
		echo "$PRODUCT" > strings/0x409/product
		mkdir functions/accessory.usb0
		mkdir configs/c.1
		echo 500 > configs/c.1/MaxPower
		ln -s functions/accessory.usb0 configs/c.1
	fi

	# Setup default config
	cd /sys/kernel/config/usb_gadget
	if [ ! -d "$DEFAULT_GADGET_NAME" ]; then
		mkdir "$DEFAULT_GADGET_NAME"
		cd "$DEFAULT_GADGET_NAME"
		echo "$VENDOR_ID" > idVendor
		echo "$PRODUCT_ID" > idProduct
		mkdir strings/0x409
		echo "$SERIAL_NUMBER" > strings/0x409/serialnumber
		echo "$MANUFACTURER" > strings/0x409/manufacturer
		echo "$PRODUCT" > strings/0x409/product
		mkdir functions/ffs.mtp
		mkdir configs/c.1
		echo 500 > configs/c.1/MaxPower
		ln -s functions/ffs.mtp configs/c.1
	fi

	logger -s -p INFO -t gadget_define USB gadget configuration defined
}

stop() {
	cd /sys/kernel/config/usb_gadget
	rm -r "$ACCESSORY_GADGET_NAME"
	rm -r "$DEFAULT_GADGET_NAME"

	logger -s -p INFO -t gadget_define USB gadget configurstion deleted
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	*)
		echo "Usage: $0 {start|stop}"
		;;
esac

exit $RETVAL
