#!/bin/sh
#
# Manage uMTPrd daemon
#

FUNCTIONFS_PATH=/dev/ffs-mtp
DAEMON=umtprd
PIDFILE="/var/run/$DAEMON.pid"

RETVAL=0

start() {
    # Mount FunctionFS and start uMTPrd
    if [ ! -f "$FUNCTIONFS_PATH" ]; then
        mkdir "$FUNCTIONFS_PATH"
    fi
    mount -t functionfs mtp "$FUNCTIONFS_PATH"
    start-stop-daemon -S -b -q -m -p "$PIDFILE" -x "/usr/sbin/$DAEMON"
    RETVAL=$?

	logger -s -p INFO -t uMTPrd Started uMTPrd daemon
}

stop() {
    start-stop-daemon -K -q -s 9 -p "$PIDFILE"
    RETVAL=$?
    umount "$FUNCTIONFS_PATH"
    rm -r "$FUNCTIONFS_PATH"
    logger -s -p INFO -t uMTPrd Stopped uMTPrd daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	*)
		echo "Usage: $0 {start|stop}"
		;;
esac

exit $RETVAL