#!/bin/sh
#
# Mange Android Accessory events and lifecycle
#

DAEMON="uevent"
PIDFILE="/var/run/$DAEMON-gadget.pid"


RETVAL=0

case "$1" in
	start)
		start-stop-daemon -S -b -q -m -p "$PIDFILE" -x "/sbin/$DAEMON" -- "sh" "/root/enable_gadget.sh"
		RETVAL=$?
		;;
	stop)
		start-stop-daemon -K -q -p "$PIDFILE"
		RETVAL=$?
		;;
	*)
		echo "Usage: $0 {start|stop}"
		;;
esac

exit $RETVAL
