name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        defconfig:
        - raspberrypi0w
        - raspberrypizero2w
        - raspberrypi4
        - raspberrypi3a

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache buildroot output
      uses: actions/cache@v2
      with:
        path: ./buildroot/output
        key: ${{ runner.os }}-build-${{ hashFiles('**/Makefile') }}

    - name: Cache buildroot downloads
      uses: actions/cache@v2
      with:
        path: ./buildroot/dl
        key: ${{ runner.os }}-dl-${{ hashFiles('**/Makefile') }}

    - name: Cache buildroot build
      uses: actions/cache@v2
      with:
        path: ./buildroot/build
        key: ${{ runner.os }}-build-${{ hashFiles('**/Makefile') }}

    - name: Setup config
      run: make BR2_EXTERNAL=../aa_wireless_dongle/ ${{ matrix.defconfig }}_defconfig
      working-directory: ./buildroot

    - name: Build
      run: make -j2
      working-directory: ./buildroot

    - name: Compress sdcard.img
      run: xz -c sdcard.img > ${{ matrix.defconfig }}-sdcard.img.xz
      working-directory: ./buildroot/output/images

    - uses: actions/upload-artifact@v3
      with:
        name: AAWirelessDongle
        path: ./buildroot/output/images/${{ matrix.defconfig }}-sdcard.img.xz
