name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        defconfig:
        - raspberrypi0w
        - raspberrypizero2w
        - raspberrypi4
        - raspberrypi3a

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Print Variables
      run: |
        echo Runner OS: ${{ runner.os }}
        echo Matrix Defconfig: ${{ matrix.defconfig }}
        echo Hash of Makefile: ${{ hashFiles('**/Makefile') }}

    - name: Cache buildroot output
      uses: actions/cache@v3
      with:
        path: ./buildroot/output
        key: ${{ runner.os }}-output-${{ matrix.defconfig }}-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-output-${{ hashFiles('**/Makefile') }}

    - name: Cache buildroot downloads
      uses: actions/cache@v3
      with:
        path: ./buildroot/dl
        key: ${{ runner.os }}-dl-${{ matrix.defconfig }}-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-dl-${{ hashFiles('**/Makefile') }}

    - name: Print hash after cache
      run: | 
        echo Hash of Makefile: ${{ hashFiles('**/Makefile') }}

    - name: Cache buildroot build
      uses: actions/cache@v3
      with:
        path: ./buildroot/build
        key: ${{ runner.os }}-build-${{ matrix.defconfig }}-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ hashFiles('**/Makefile') }}

    - name: Setup config
      run: make BR2_EXTERNAL=../aa_wireless_dongle/ ${{ matrix.defconfig }}_defconfig
      working-directory: ./buildroot

    - name: Build
      run: make -j2
      working-directory: ./buildroot

    - name: Compress sdcard.img
      run: xz -c sdcard.img > ${{ matrix.defconfig }}-sdcard.img.xz
      working-directory: ./buildroot/output/images

    - uses: actions/upload-artifact@v4
      with:
        name: AAWirelessDongle
        path: ./buildroot/output/images/${{ matrix.defconfig }}-sdcard.img.xz
